Course.find_or_create_by(name: "Alpine Golf",location: 0)
Course.find_or_create_by(name: "Amata Spring Golf",location: 1)
Course.find_or_create_by(name: "Ayutthaya Golf",location: 2)
Course.find_or_create_by(name: "Thai Country",location: 0)
Course.find_or_create_by(name: "Vintage Club",location: 0)
Course.find_or_create_by(name: "Siam Country(Old)",location: 1)
Course.find_or_create_by(name: "Siam Country(Plantation)",location: 1)
Course.find_or_create_by(name: "Siam Country(WaterSide)",location: 1)
Course.find_or_create_by(name: "The Pine & Lodge",location: 0)
Course.find_or_create_by(name: "Royal Lake Side",location: 1)
Course.find_or_create_by(name: "Windsor Park Golf",location: 1)
Course.find_or_create_by(name: "Cascata Golf",location: 0)
Course.find_or_create_by(name: "Kiarti Thanee Country",location: 0)
Course.find_or_create_by(name: "Green Valley Country",location: 0)
Course.find_or_create_by(name: "Krung Kavee Golf",location: 0)
Course.find_or_create_by(name: "Krungthep Kreetha Golf",location: 0)
Course.find_or_create_by(name: "Summit Windmill",location: 0)
Course.find_or_create_by(name: "Subhapruek Golf",location: 0)
Course.find_or_create_by(name: "Swan Golf Country",location: 4)
Course.find_or_create_by(name: "Thana City Golf",location: 0)
Course.find_or_create_by(name: "Thanon Golf",location: 0)
Course.find_or_create_by(name: "Subhapruek Golf",location: 0)
Course.find_or_create_by(name: "Thanya Golf",location: 0)
Course.find_or_create_by(name: "Flora Ville Golf",location: 2)
Course.find_or_create_by(name: "Navatanee Golf",location: 2)
Course.find_or_create_by(name: "Northern Rangsit",location: 2)
Course.find_or_create_by(name: "Pinehurst Golf",location: 2)
Course.find_or_create_by(name: "Bangkok Golf",location: 0)
Course.find_or_create_by(name: "Bangpakong Riverside",location: 1)
Course.find_or_create_by(name: "Bangpoo Golf",location: 0)
Course.find_or_create_by(name: "Panyaindora Golf",location: 0)
Course.find_or_create_by(name: "Best Ocean",location: 4)
Course.find_or_create_by(name: "Muang Kaew Golf",location: 0)
Course.find_or_create_by(name: "Unico Grande Golf",location: 0)
Course.find_or_create_by(name: "Uniland Golf",location: 4)
Course.find_or_create_by(name: "Ratchakram Golf",location: 4)
Course.find_or_create_by(name: "Riverdale Golf",location: 0)
Course.find_or_create_by(name: "Lakewood Golf",location: 0)
Course.find_or_create_by(name: "Legacy Golf",location: 4)
Course.find_or_create_by(name: "Royal Golf",location: 0)
Course.find_or_create_by(name: "Royal Gems Golf",location: 4)
Course.find_or_create_by(name: "Royal Gems Golf City",location: 2)
Course.find_or_create_by(name: "Rose Garden",location: 4)
Course.find_or_create_by(name: "Lotus Valley",location: 2)

Course.find_or_create_by(name: "Khao Kheow Country",location: 1)
Course.find_or_create_by(name: "Green Wood Golf",location: 1)
Course.find_or_create_by(name: "St.Andrews2000 Golf",location: 1)
Course.find_or_create_by(name: "Patana Golf",location: 1)
Course.find_or_create_by(name: "Pattaya Country",location: 1)
Course.find_or_create_by(name: "Bangpra Golf",location: 1)
Course.find_or_create_by(name: "Wangjuntr Golf Park",location: 1)
Course.find_or_create_by(name: "Phoenix Golf",location: 1)
Course.find_or_create_by(name: "Burapha Golf",location: 1)
Course.find_or_create_by(name: "Pleasant Valley Golf",location: 1)
Course.find_or_create_by(name: "Chrystal Bay Golf",location: 1)
Course.find_or_create_by(name: "Mountain Shadow Golf",location: 1)
Course.find_or_create_by(name: "Rayong Green Valley",location: 1)
Course.find_or_create_by(name: "Leamchabang Country",location: 1)
Course.find_or_create_by(name: "Bangsai Country Club",location: 2)
Course.find_or_create_by(name: "Muang Ake Golf",location: 2)
Course.find_or_create_by(name: "Muang Ake Vista Golf",location: 2)
Course.find_or_create_by(name: "Army Sport CenterⅡ",location: 2)
Course.find_or_create_by(name: "Black Mountain",location: 4)
Course.find_or_create_by(name: "Banyan Golf Club",location: 4)
Course.find_or_create_by(name: "Dhanarat Golf Club",location: 4)
Course.find_or_create_by(name: "Eagle Milford Golf Course",location: 4)
Course.find_or_create_by(name: "Royal Hua Hin Golf Course",location: 4)
Course.find_or_create_by(name: "NCR Country",location: 2)
Course.find_or_create_by(name: "Nikanti Golf Club",location: 4)
Course.find_or_create_by(name: "Parichat Golf Links",location: 1)
Course.find_or_create_by(name: "Singha Park Khonkaen Golf",location: 4)
Course.find_or_create_by(name: "Watermill Golf",location: 4)
Course.find_or_create_by(name: "Khao Cha-Ngok Golf",location: 4)
Course.find_or_create_by(name: "Artitaya Golf ",location: 4)
Course.find_or_create_by(name: "Lakewood Links ",location: 0)